### ISSUE TITLE
Content view y is negative after action finished

### ISSUE THREAD

**Issue by hivinau** [WXGBridgeQ/SwiftPullToRefresh#20] opened 2018-07-31 07:47 UTC
![Expected result](https://user-images.githubusercontent.com/11225721/43445424-9abb050c-94a6-11e8-91b7-4b0fe5f299c7.png)
![Result issue](https://user-images.githubusercontent.com/11225721/43445434-9da200a4-94a6-11e8-9de0-0579a49756b6.png)

**Comment by WXGBridgeQ** [comment] 2018-10-08 09:45
@hivinau 
Sorry, can't reproduce on my side, I'll close it now.
Feel free to re-open it if you can provide more details.

**Closed by WXGBridgeQ** 2018-10-08 09:45 UTC
Labels: bug
